mass_arm: [100,0,0,0,0,0,
           0,100,0,0,0,0,
           0,0,100,0,0,0,
           0,0,0,100,0,0,
           0,0,0,0,100,0,
           0,0,0,0,0,100]
damping_arm: [2000,0,0,0,0,0,
              0,2000,0,0,0,0,
              0,0,2000,0,0,0,
              0,0,0,2000,0,0,
              0,0,0,0,2000,0,
              0,0,0,0,0,2000]
stiffness_coupling: [0,0,0,0,0,0,
                     0,0,0,0,0,0,
                     0,0,0,0,0,0,
                     0,0,0,0,0,0,
                     0,0,0,0,0,0,
                     0,0,0,0,0,0]

base_link: "base_link"
end_link: "tool0"
# [position (x, y, z)  orientation (x, y, z, w)]
desired_pose:  [0,0,0.026,       -0.11, 0.99, 0.002, 0.009]

workspace_limits: [-0.50, 0.50, 0.25, 0.80, 0.30, 0.75]

arm_max_vel: 1.5
arm_max_acc: 3.0
platform_max_vel: 0.1
platform_max_acc: 0.2